amadventure/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls')),
    path('user/', include('usersystem.urls')),
]

game/urls.py
from django.urls import path
from . import views


app_name = 'game'

urlpatterns = [
    path('', views.WelcomeView.as_view(), name='main'),
    path('hero/create/', views.CreateHeroView.as_view(), name='create_hero'),
    path('hero/upgrade/', views.UpgradeHeroView.as_view(), name='upgrade_hero'),
    path('hero/list/', views.HeroList.as_view(), name='hero_list'),
    path('hero/owned/', views.HeroOwned.as_view(), name='hero_owned'),
    path('hero/<int:pk>/', views.HeroDetail.as_view(), name='hero_detail'),
    path('hero/fight/<int:defender_pk>/', views.FightView.as_view(), name='hero_fight'),
    path('hero/delete/<int:pk>/', views.HeroDeleteView.as_view(), name='hero_delete'),
]

usersystem/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'usersystem'

urlpatterns = [
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('sign_in/', views.SignInView.as_view(), name='sign_in'),
    path('sign_out/', auth_views.LogoutView.as_view(), name='sign_out'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Amadventure - {% block title %}{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Amadventure is a web browser game taking place in mythic world.">
        <!-- Google fronts api -->
        <!-- call: font-family: 'Sarabun', sans-serif; -->
        <link href="https://fonts.googleapis.com/css?family=Sarabun" rel="stylesheet">
        <!-- shortcut icon -->
        <link rel="shortcut icon" type="image/png" href="https://res.cloudinary.com/hostingsme/image/upload/v1549034217/Amadventure-favicon.png"/>
         <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
        {% block styles %}{% endblock %}
    </head>
    <body>
        
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="d-flex flex-column">

                <div class="d-flex">
                    <div class="p-2 logo">
                        <img src="https://res.cloudinary.com/hostingsme/image/upload/v1549034221/Amadventure-logo.png">
                    </div>
                    <div>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                </div>

                <div class="collapse navbar-collapse mx-auto mx-lg-0" id="navbarTogglerDemo01">
                    <ul class="navbar-nav mr-auto mt-2 d-flex">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'game:main' %}">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'game:hero_owned' %}">Your hero</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'game:hero_list' %}">Heroes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Locations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'usersystem:sign_out' %}">Sign out</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'usersystem:sign_in' %}">Sign in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'usersystem:sign_up' %}">Sign up</a>
                            </li>
                        {% endif %}
                    </ul> 
                </div>

            </div>
        </nav>

        <main>
            <div class="container">
                    {% block content %}{% endblock %}
            </div>
        </main>

        <footer>
            <!--Created by: -->
        </footer>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>